// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouercroxkpghwcttypod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91ZXJjcm94a3BnaHdjdHR5cG9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzY4NDksImV4cCI6MjA2NjM1Mjg0OX0.URksaWrJK5SjWIbacvCFN-KA3V6XexLQEg8fiCgX_jA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);